form/urls.py
from django.urls import path

from . import views
app_name = 'form'

urlpatterns =[
    path('homepage/', views.homepage, name="homepage"),
    path('create/', views.create, name='create'),
    path('index/', views.index, name='index'),
    path('detail/P<id_post>/', views.detail, name='detail'),
    path('delete/P<id_post>/', views.delete, name='delete'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('edu/', views.edu, name='edu'),
    path('profil/', views.profil, name='profil'),
  
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('form/', include('form.urls', namespace='form')),
    path('story6/', include('story6.urls', namespace='story6')),
]

story6/urls.py
from django.urls import path

from . import views
app_name = 'story6'

urlpatterns =[
    path('index/', views.index, name="index"),
    path('add/', views.add, name='add'),
    path('list/', views.listnya, name='list'),
    path('regist/<int:id_post>/', views.regist, name='regist'),
    path('delete/<int:id_post>/', views.delete, name='delete'),
]

form/models.py
from django.db import models

# Create your models here.
class PostModel(models.Model):
    mata_kuliah   =models.CharField(max_length=50)
    dosen         =models.CharField(max_length=50)
    jumlah_sks   =models.IntegerField()
    deskripsi_matkul    =models.CharField(max_length=100)
    semester         =models.IntegerField()
    ruang_kelas      =models.CharField(max_length=50)

    def __str__(self):
        return self.mata_kuliah

main/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    n_kegiatan = models.CharField(max_length=100)
    desk_kegiatan = models.CharField(max_length=100)
    
    def __str__(self):
        return self.n_kegiatan

class Orang(models.Model):
    nama_orang = models.CharField(max_length=100)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.nama_orang

form/forms.py
from django import forms

class PostForm(forms.Form):
    mata_kuliah =forms.CharField(
        label = "Nama Mata Kuliah",
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    dosen         =forms.CharField(
        label = "Dosen",
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    jumlah_sks   =forms.CharField(
        label = "Jumlah SKS",
        max_length=50,
        widget=forms.NumberInput(
            attrs={
            'class':'form-control',
            'min':'1',
            'max':'6',
            }
        )
    )
    deskripsi_matkul    =forms.CharField(
        label = "Deskripsi mata kuliah",
        max_length=50,
        widget = forms.Textarea(
            attrs={
                'class':'form-control',
            }
        )
    )
    semester         =forms.CharField(
        label = "Semester",
        max_length=50,
        widget=forms.NumberInput(
            attrs={
            'class':'form-control',
            'min':'1',
            'max':'8',
            }
        )
    )
    ruang_kelas      =forms.CharField(
        label = "Ruang kelas",
        max_length=50,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    

story6/forms.py
from django import forms

class FormKegiatan(forms.Form):
    n_kegiatan=forms.CharField(
        label = "Nama Kegiatan",
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    desk_kegiatan=forms.CharField(
        label = "Deskripsi Kegiatan",
        max_length=100,
        widget=forms.Textarea(
            attrs={
                'class':'form-control',
            }
        )
    )

class FormOrang(forms.Form):
    nama_orang   =forms.CharField(
        label = "Nama Orang",
        max_length=100,
        widget=forms.TextInput(
            attrs={
            'class':'form-control',
            }
        )
    )
    

form/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
# Create your views here.
from .forms import PostForm
from .models import PostModel

def homepage(request):
    return render(request, 'form/homepage.html')

def index(request):
    posts = PostModel.objects.all()
    context = {
        'page_title':"Jadwal",
        'posts':posts,
    }
    return render(request, 'form/index.html', context)

def create(request):
    post_form = PostForm(request.POST or None)

    if post_form.is_valid():
        if request.method == 'POST':
            PostModel.objects.create(
                mata_kuliah = post_form.cleaned_data.get('mata_kuliah'),
                dosen = post_form.cleaned_data.get('dosen'),
                jumlah_sks = post_form.cleaned_data.get('jumlah_sks'),
                deskripsi_matkul = post_form.cleaned_data.get('deskripsi_matkul'),
                semester = post_form.cleaned_data.get('semester'),
                ruang_kelas = post_form.cleaned_data.get('ruang_kelas'),
            )
            return HttpResponseRedirect("/form/index/")

    context = {
        'page_title':'Add Courses',
        'post_form':post_form
    }
    return render(request, 'form/create.html', context)

def detail(request, id_post):
    matkul = PostModel.objects.filter(id=id_post).get(id=id_post)
    response = {
        'post':matkul
    }
    return render(request, 'form/detail.html', response)

def delete(request, id_post):
    try:
        delete_courses = PostModel.objects.filter(id = id_post)
        delete_courses.delete()
        return redirect('form:index')
    except:
        return redirect('form:index')

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

def edu(request):
    return render(request, 'main/edu.html')

def profil(request):
    return render(request, 'main/profil.html')

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import FormKegiatan, FormOrang
from .models import Kegiatan, Orang
# Create your views here.

def index(request):
    return render(request, 'story6/index.html')

def listnya(request):
    kegiatan = Kegiatan.objects.all()
    orang = Orang.objects.all()

    return render(request, 'story6/list.html', {'kegiatan': kegiatan, 'orang': orang})

def add(request):
    form_kegiatan = FormKegiatan(request.POST or None)

    if form_kegiatan.is_valid():
        if request.method == 'POST':
            Kegiatan.objects.create(
                n_kegiatan = form_kegiatan.cleaned_data.get('n_kegiatan'),
                desk_kegiatan = form_kegiatan.cleaned_data.get('desk_kegiatan'),
            )
            return HttpResponseRedirect("/story6/list/")

    context = {
        'page_title':'Add Kegiatan',
        'form_kegiatan':form_kegiatan
    }
    return render(request, 'story6/add.html', context)

def regist(request, id_post):
    form_orang = FormOrang(request.POST or None)

    if form_orang.is_valid():
        if request.method == 'POST':
            data_orang = form_orang.cleaned_data
            orang_regist = Orang()
            orang_regist.nama_orang = data_orang['nama_orang']
            orang_regist.kegiatan = Kegiatan.objects.get(id=id_post)
            orang_regist.save()
            return redirect('/story6/list')
    
    context = {
        'page_title':'Register',
        'form_orang':form_orang
    }
    return render(request, 'story6/regist.html', context)
        
def delete(request, id_post):
    delete_user = Orang.objects.filter(id = id_post)
    delete_user.delete()
    return redirect('story6:list')

form/templates/form/create.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
    {{page_title}}
{% endblock page_title %}
{% endblock meta %}

{% block content %}
<div class="container-fluid">
    <h1>{{page_title}}</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{post_form.as_table}}
        </table>
        <button type = "Submit">Add</button>
    </form>
</div>
{% endblock content %}

form/templates/form/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
    {{page_title}}
{% endblock page_title %}
{% endblock meta %}


{% block content %}
<h3 class="mt-5 text-center edu">DETAILS</h3>
<hr>
<div class="container">
  <table class="table">
    <tr>
      <td>Mata Kuliah : </td>
      <td>{{post.mata_kuliah}}</td>
    </tr>
    <tr>
      <td>Nama Dosen : </td>
      <td>{{post.dosen}}</td>
    </tr>
    <tr>
      <td>Jumlah SKS : </td>
      <td>{{post.jumlah_sks}}</td>
    </tr>
    <tr>
      <td>Deskripsi : </td>
      <td>{{post.deskripsi_matkul}}</td>
    </tr>
    <tr>
      <td>Semester : </td>
      <td>{{post.semester}}</td>
    </tr>
    <tr>
      <td>Ruang Kelas : </td>
      <td>{{post.ruang_kelas}}</td>
    </tr>
</table> 
</div>
{% endblock content %}

form/templates/form/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Courses</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">MyCourses</h1>
        <p class="lead">Hello! This is my University Courses!</p>
        <hr class="my-4">
        <p>If you want to add new subject and see the subject click the button below!</p>
        <a class="btn btn-primary btn-lg" href="/form/create" role="button">Add new Courses!</a>
        <a class="btn btn-primary btn-lg" href="/form/index" role="button">See my Courses!</a>
    </div>
</div>

{% endblock content %}

form/templates/form/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
    {{page_title}}
{% endblock page_title %}
{% endblock meta %}


{% block content %}
<div class="container-fluid">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Mata Kuliah</th>
            <th scope="col">Nama Dosen</th>
            <th scope="col">Jumlah SKS</th>
            <th scope="col">Deskripsi</th>
            <th scope="col">Semester</th>
            <th scope="col">Ruang Kelas</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
            {% for post in posts %}
          <tr>
            <td><a href="{% url 'form:detail' post.id %}">{{post.mata_kuliah}}</a></td>
            <td>{{post.dosen}}</td>
            <td>{{post.jumlah_sks}}</td>
            <td>{{post.deskripsi_matkul}}</td>
            <td>{{post.semester}}</td>
            <td>{{post.ruang_kelas}}</td>
            <td>
              <a href="{% url 'form:delete' post.id %}" class="btn btn-light">Delete</a>
            </td>
          </tr>
            {% endfor %}
        </tbody>
      </table>
{% endblock content %}

main/templates/main/edu.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Education</title>
{% endblock meta %}

{% block content %}
    <!--EDUCATION-->
    <h3 class="mt-5 text-center edu" id="edu">EDUCATION</h3>
    <hr>
    <div class="container text-center" id="edu">
      <table class="table table-bordered mt-5">
        <thead>
          <tr>
            <th scope="col"><h4>No.</h4></th>
            <th scope="col"><h4>Education</h4></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>SDN Jatinegara Kaum 01 Pagi (2007-2013)</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>SMPN 255 Jakarta (2013-2016)</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>SMAN 21 Jakarta (2016-2019)</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'img/smp.jpg' %}" class="d-block w-100" alt="smp">
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/sma.jpg' %}" class="d-block w-100" alt="sma">
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/kuliah.jpg' %}" class="d-block w-100" alt="kuliah">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Tsanaa's Web</title>
{% endblock meta %}

{% block content %} 
<!--Bootstrap Navbar-->
<!-- <header class="header fixed-top">
  <nav class="navbar navbar-expand-lg sticky-top navbar-light">
      <div class="container">
      <a class="navbar-brand " href="#home"><strong>TSANAA</strong></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
              <a class="nav-link" href="#about">ABOUT</a>
              <a class="nav-link" href="#skill">SKILLS</a>
              <a class="nav-link" href="#experience">EXPERIENCE</a>
              <a class="nav-link" href="#contact">CONTACT</a>
              <a class="nav-link" href="{% url 'main:profil' %}">PROFILE</a>
              <a class="nav-link" href="{% url 'main:edu' %}">EDUCATION</a>
          </div>
      </div>
      </div>
  </nav>
</header> -->

  <!--HOME-->
    <div class="container-home" id="home">
      <img src="{% static 'img/home.jpg' %}" class="img-fluid" alt="Responsive image">
      <div class="centered">WELCOME</div>
    </div>

    <!--ABOUT-->
    <div class="container" id="about">
      <div class="row">
        <div class="col-md-6 content mt-5">
          <img src="{% static 'img/about.jpg' %}" class="img-fluid" alt="Responsive image">
        </div>
        <div class="col-md-6 text-center content-text mt-5">
          <h4>My name is Tsanaa Patricia Khonsaa. You can call me Tsanaa. I am 20 years old. I am currently studying at the University of Indonesia majoring in Information System class of 2019.</h4>
          <h4 class="mb-0">I'm interested in digital marketing, user experience, and product management.  I increase my knowledge about these things through seminars and find out for myself.</h4>
        </div>
      </div>
    </div>

    <!--SKILLS-->
    <h3 class="mt-5 text-center skill" id="skill">SKILLS</h3>
    <hr>
      <div class="container" id="skill">
        <div class="row text-center mt-5">
          <div class="col-md-4">
            <img src="{% static 'img/digitalmarketing.png' %}" alt="dgm">
            <h4>Digital Marketing</h4>
          </div>
          <div class="col-md-4">
            <img src="{% static 'img/coding.png' %}" alt="coding">
            <h4>Basic Programming</h4>
          </div>
          <div class="col-md-4">
            <img src="{% static 'img/language.png' %}" alt="language">
            <h4>Language (Indonesia and English)</h4>
          </div>
          <div class="col-md-4">
            <img src="{% static 'img/fastresponses.png' %}" alt="fastrep">
            <h4>Fast Response</h4>
          </div>
          <div class="col-md-4">
            <img src="{% static 'img/discipline.png' %}" alt="discipline">
            <h4>Discipline</h4>
          </div>
          <div class="col-md-4">
            <img src="{% static 'img/conversation.png' %}" alt="comm">
            <h4>Communication</h4>
          </div>
        </div>
      </div>

    <!--EXPERIENCE-->
    <h3 class="mt-5 text-center exp" id="experience">EXPERIENCE</h3>
    <hr>
        <br>
        <blockquote class="blockquote text-center" id="experience">
          <p class="mb-0">Staff of Public Relations at Syukuran dan Pelepasan Wisudawan Fasilkom UI</p>
          <footer class="blockquote-footer">September 2020 until Now</footer>
          <br>
          <p class="mb-0">Staff of Dana Konsumsi at Open House Fasilkom UI</p>
          <footer class="blockquote-footer">September 2020 until Now</footer>
          <br>
          <p class="mb-0">Staff of Digital Marketing at COMPFEST</p>
          <footer class="blockquote-footer">February 2020 until Now</footer>
          <br>
          <p class="mb-0">Staff of Public Relations at Syukuran dan Pelepasan Wisudawan Fasilkom UI</p>
          <footer class="blockquote-footer">December 2019 until January 2020</footer>
          <br>
        </blockquote>

    <!--CONTACT-->
    <h3 class="mt-5 text-center contact" id="contact">CONTACT</h3>
    <hr>
    <div class="container" id="contact">
      <div class="row text-center mt-5">
        <div class="col-md-4">
          <a href="https://www.linkedin.com/in/tsanaa-patricia-5a85761a2/"><img src="{% static 'img/linkedin.png' %}" alt="linkedin"></a>
        </div>
        <div class="col-md-4">
          <a href="mailto:patriciakhonsaa@gmail.com"><img src="{% static 'img/email.png' %}" alt="email"></a>
        </div>
        <div class="col-md-4">
          <a href="https://www.instagram.com/tsanaapk/?hl=id"><img src="{% static 'img/instagram.png' %}" alt="ig"></a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

main/templates/main/profil.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>My Profile</title> 
    <link href='https://fonts.googleapis.com/css?family=Bungee Shade' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Fanwood Text' rel='stylesheet'>
    <style>
        body {
          background-color:white;
          font-family: 'Fanwood Text';
          font-size: 22px;
          color:black;
        }

        .fotoumum{
            display: flex;
            justify-content: center;
        }

        .fotoumum img{
            display: flex; 
            justify-content: center;
            height: 15%; width: 20%;
        }

        .socialmedia{
            margin-left: 190px; margin-right: auto;
        }

        table, th, td {
            display: flex;
            justify-content: center;
            border: 1px solid black;
            border-collapse: collapse;
        }
        
        h1 {
          color:black;
          text-align:center;
          font-family: 'Bungee Shade';
          font-size: 25px;
          margin-top:3%;
          margin-bottom: 5%;
        }
        
        p {
            color:black;
            text-align: center;
            font-family: 'Fanwood Text';
            font-size: 22px;
        }
        #header{
            background: #70DECA; 
            height: 150px; width: 500px; margin:auto;
        }
        #wrap {
            background: #70DECA; 
            height: 680px; width: 500px; margin: auto;
        }
    </style>

</head>

<body>
    <br><br>
    <h1>THIS IS ME</h1>
    <div class="fotoumum">
        <img src = "https://i.postimg.cc/ZKm3Ccss/JP50.jpg" />
    </div>
    

   
    <div id="header">
        <p>Hello! My name is Tsanaa Patricia Khonsaa. I am usually called Tsanaa. I was born in Banyuwangi on 25 September 2000. I am an only child. I am a humorous and cheerful person. I am currently studying at Fasilkom UI majoring in Information Systems. Below is my short bio.</p>
    </div>

    <div id="wrap">
        <h1>MY SHORT BIO</h1>
        <p>Name: Tsanaa Patricia Khonsaa</p>
        <p>Student number: 1906353914</p>
        <p>Class of: 2019</p>
        <p>Hobby: watch movies, drama, and series</p>

        <h1>EDUCATIONAL BACKGROUND </h1>
        <table style="width:100%">
            <tr>
                <th align="center">Education</th>
            </tr>
            <tr>
                <td align="center">SDN Jatinegara Kaum 01 Pagi (2007-2013) </td>
            </tr>
            <tr>
                <td align="center">SMPN 255 Jakarta (2013-2016) </td>
            </tr>
            <tr>
                <td align="center">SMAN 21 Jakarta (2016-2019)</td>
            </tr>
        </table>

        <p>Click the icon below, to view my social media accounts! </p>
        <div class="socialmedia">
            <a href="https://www.instagram.com/tsanaapk/?hl=id"><img src="{% static 'img/insta.png'%}" height="50" width="50" /></a>
            <a href="https://www.linkedin.com/in/tsanaa-patricia-5a85761a2/"><img src="{% static 'img/linked.png'%}" height="50" width="50"/></a>
        </div>
    </div>

</body>
{% endblock content %}
</html>

story6/templates/story6/add.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
    {{page_title}}
{% endblock page_title %}
{% endblock meta %}

{% block content %}
<div class="container-fluid">
    <h1>{{page_title}}</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{form_kegiatan.as_table}}
        </table>
        <button type = "Submit">Add</button>
    </form>
</div>
{% endblock content %}

story6/templates/story6/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Activities</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">MyActivities</h1>
        <p class="lead">Hello! This is my Activities!</p>
        <hr class="my-4">
        <p>If you want to add new activity and see the ativities click the button below!</p>
        <a class="btn btn-primary btn-lg" href="/story6/add" role="button">Add new Activity!</a>
        <a class="btn btn-primary btn-lg" href="/story6/list" role="button">See my Activities!</a>
    </div>
</div>

{% endblock content %}

story6/templates/story6/list.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
    {{page_title}}
{% endblock page_title %}
{% endblock meta %}


{% block content %}
<div class="container">
{% for x in kegiatan %}
  <div class="col-4 m-4 p-4">
    <ul class="list-group">
      <li class="list-group-item"><b>{{ x.n_kegiatan }}</b></li>

      {% for y in orang %}
      {% if y.kegiatan == x %}
      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          {{ y.nama_orang }}
            <a href="{% url 'story6:delete' id_post=y.pk %}" class="btn btn-light"><button>Delete</button></a>
        </div>
      </li>
      {% endif %}
      {% endfor %}
    </ul>
    <a href="{% url 'story6:regist' id_post=x.pk %}" ><button>Register!</button></a>
  </div>
  {% endfor %}
</div>
{% endblock content %}

story6/templates/story6/regist.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
    {{page_title}}
{% endblock page_title %}
{% endblock meta %}


{% block content %}
<div class="container-fluid">
    <h1>{{page_title}}</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{form_orang.as_table}}
        </table>
        <button type = "Submit">Add</button>
    </form>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<!--Bootstrap Navbar-->
<body>
  <header class="header fixed-top">
    <nav class="navbar navbar-expand-lg sticky-top navbar-light">
      <div class="container">
        <a class="navbar-brand " href="{% url 'main:home' %}"><strong>TSANAA</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-link" href="{% url 'main:profil' %}">PROFILE</a>
            <a class="nav-link" href="{% url 'main:edu' %}">EDUCATION</a>
            <a class="nav-link" href="{% url 'form:homepage' %}">COURSES</a>
            <a class="nav-link" href="{% url 'story6:index' %}">ACTIVITIES</a>
          </div>
        </div>
      </div>
    </nav>
  </header>

  

  {% block content %}
  {% endblock content %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>